services:
  auction-db:
    image: postgres
    container_name: auction-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=auction-db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  search-db:
    image: mongo
    container_name: search-db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
      - MONGO_INITDB_DATABASE=search-db
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
  event-bus:
    image: rabbitmq:4.0.6-management-alpine #gui, lightweight
    container_name: event-bus
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672 #browser gui
volumes:
  pgdata:
  mongodata: